### ISSUE TITLE
sky-list-toolbar displays an empty box when searchEnabled=false

### ISSUE THREAD

**Issue by Blackbaud-DavidCollura** [blackbaud/skyux-list-builder-view-checklist#37]
### Expected behavior
sky-list-toolbar-item elements should display in the first grey box of the toolbar

### Actual behavior
sky-list-toolbar-item elements display in a second grey box of the toolbar, under a first grey box which is empty

### Steps to reproduce
Implement a sky-list containing a sky-list-toolbar with searchEnabled=false.
Then, add a sky-list-toolbar-item to the sky-list-toolbar.

Sample code which produced the error:
```
<sky-list *ngIf="volunteerStream.value.length"
      [data]="volunteerStream" [selectedIds]="volsInitial"
      (selectedIdsChange)="selectedItemsChange($event)">
        <sky-list-toolbar [searchEnabled]="false" toolbarType="standard">
            <sky-list-toolbar-item location="left" index="0">
                <ng-template>
                  Hello world.
                </ng-template>
            </sky-list-toolbar-item>
        </sky-list-toolbar>
        <sky-list-view-checklist selectMode="multiple">
        </sky-list-view-checklist>
      </sky-list>
```

### Severity
Medium

### Impact
Medium

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux/list-builder` version `3.7.1`
