### ISSUE TITLE
Checklist item descriptions are truncated. The description should wrap. 

### ISSUE THREAD

**Issue by Blackbaud-VinLanzolla** [blackbaud/skyux-list-builder-view-checklist#38]

**Comment by Blackbaud-SteveBrush** [comment]
Per @Blackbaud-ToddRoberts's recommendation, you should use the repeater component instead.

**Comment by Blackbaud-VinLanzolla** [comment]
I can't use the repeater component in the Column Chooser. My understanding is that the Checkbox component doesn't wrap, therefore the Column chooser doesn't wrap.

**Comment by Blackbaud-ToddRoberts** [comment]
I believe we are updating column chooser such that it will use repeater, is that correct @Blackbaud-ErikaMcVey ?
