### ISSUE TITLE
Console error thrown in consuming SPAs when using Mac

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-list-builder-view-checklist#7]
### Actual behavior
The console throws an `ExpressionChangedAfterItHasBeenCheckedError` error when checklist is shown.

### Steps to reproduce
Create a grid with the column picker. Open the column picker and look in your console to see the error.

**Comment by Blackbaud-SteveBrush** [comment]
This only happens on a Mac.

**Comment by Blackbaud-TrevorBurch** [comment]
Could not reproduce on 4/17/19.
